name: Hello Pipeline ğŸ‘‹ (Multi-Stage)

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Enter a custom message"
        required: true
        default: "Hello from Noumanâ€™s pipeline!"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "ğŸ‘‹ ${{ github.event.inputs.message }}"

  build:
    runs-on: ubuntu-latest
    needs: greet
    steps:
      - name: Simulate Build
        run: echo "ğŸ—ï¸ Building project for: ${{ github.event.inputs.message }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Simulate Deploy
        run: echo "ğŸš€ Deploying app for: ${{ github.event.inputs.message }}"
