name: Hello Pipeline ðŸ‘‹ with Parameter

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Enter a custom message"
        required: true
        default: "Hello from Noumanâ€™s CI/CD pipeline!"

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: |
          echo "ðŸ”” Message received:"
          echo "${{ github.event.inputs.message }}"
